### ISSUE TITLE
Module crash into an unrecoverable state

### ISSUE THREAD

**Issue by mneme** [Befaco/MIDIThing2#3]
Using the web editor seems to have left the module in a non-recoverable state. The screen shows "random static" and toggles on and off.

**Comment by mneme** [comment]
![IMG_2206](https://github.com/Befaco/MIDIThing2/assets/589016/f8c95beb-1fee-4bde-a899-9ec701b14ff6)

**Comment by mneme** [comment]
Well - I spoke to soon. Turns out it's recoverable by holding the encoder down as it started up and then clearing all saved configs.

**Comment by mneme** [comment]
Well - I spoke to soon. Turns out it's recoverable by holding the encoder down as it started up and then clearing all saved configs.

Might be something to add to the documentation though.

**Comment by xustafu** [comment]
> Well - I spoke to soon. Turns out it's recoverable by holding the encoder down as it started up and then clearing all saved configs.
> 
> Might be something to add to the documentation though.

There is a mention in the manual, but its true it might be good to give  this one some relevance.

WE have a couple of open issues regarding memory save. Like https://github.com/Befaco/MIDIThing2/issues/2
This might be related, as the freeze seems to be caused by corrupted memory.
Stay tunned for new firmware release in the coming days!!
